export type MBTIProfile = {
  img: string;
  name: string;
  alias: string;
  description: string;
  color: string;
  loveStyle: string;
  group: "SJ" | "NF" | "SP" | "NT";
  imgWidth?: number;
  imgHeight?: number;  
}

export const MBTIProfiles: Record<string, MBTIProfile> = {
  ENTP: {
    img: "/mbti/nt/entp.png",
    name: "討論者",
    alias: "賢くて好奇心旺盛な思想家",
    description: "賢くて好奇心旺盛な思想家。知的挑戦には必ず受けて立つ。",
    color: "text-red-500",
    loveStyle: "刺激的で退屈しない関係を求める。議論好きで、お互いに成長し合える知的なパートナーを大切にする。",
    group: "NT",
  },
  ENTJ: {
    img: "/mbti/nt/entj.png",
    name: "指揮官",
    alias: "大胆で想像力豊かな指導者",
    description: "大胆で想像力豊か、かつ強い意志を持つ指導者。常に道を見つけるか、道を切り開く。",
    color: "text-red-500",
    loveStyle: "主導権を握りたがる情熱家。高い基準を持つが、一度決めた相手には誠実で、共に目標を追い求めることを好む。",
    group: "NT",
    imgWidth: 150,
  },
  INTJ: {
    img: "/mbti/nt/intj.png",
    name: "建築家",
    alias: "戦略的な完璧主義者",
    description: "想像力が豊かで、戦略的な思考の持ち主。あらゆる物事に対して計画を立てる。",
    color: "text-red-500",
    loveStyle: "論理的で慎重。一度心を許すと深く献身的に尽くす。ベタベタするより、知的で自立した信頼関係を望む。",
    group: "NT",
    imgWidth: 150
  },
  INTP: {
    img: "/mbti/nt/intp.png",
    name: "論理学者",
    alias: "貪欲な知識欲を持つ発明家",
    description: "貪欲な知識欲を持つ革新的な発明家。",
    color: "text-red-500",
    loveStyle: "知的な繋がりを重視する。独自のペースがあるため、お互いの時間を尊重できる関係が心地よい。嘘のない率直な愛を向ける。",
    group: "NT",
    imgWidth: 110,
  },
  INFJ: {
    img: "/mbti/nf/infj.png",
    name: "提唱者",
    alias: "静かで神秘的な理想主義者",
    description: "静かで神秘的だが、人々を非常に勇気づける飽くなき理想主義者。",
    color: "text-red-500",
    loveStyle: "精神的な深いつながりを求める。相手の感情を深く理解し、誠実で献身的な愛を注ぐ。表面的な付き合いは好まない。",
    group: "NF",
    imgWidth: 110,
  },
  INFP: {
    img: "/mbti/nf/infp.png",
    name: "仲介者",
    alias: "詩的で親切な利他主義者",
    description: "詩的で親切な利他主義者。良い物事のためなら、いつでも懸命に手を差し伸べる。",
    color: "text-red-500",
    loveStyle: "ロマンチストで理想を追い求める。相手の全てを受け入れ、深い絆を大切にする。心を開くまでは慎重だが、愛はとても深い。",
    group: "NF",
    imgWidth: 140,
  },
  ENFJ: {
    img: "/mbti/nf/enfj.png",
    name: "主人公",
    alias: "カリスマ性があり人々を励ますリーダー",
    description: "カリスマ性があり、人々を励ますリーダー。聞く人を魅了する。",
    color: "text-red-500",
    loveStyle: "パートナーの幸せが自分の幸せ。コミュニケーションを大切にし、相手の成長を全力でサポートする情熱的な愛の持ち主。",
    group: "NF",
    imgWidth: 120,
  },
  ENFP: {
    img: "/mbti/nf/enfp.png",
    name: "広報運動家",
    alias: "情熱的で独創的な自由人",
    description: "情熱的で独創的、かつ社交的な自由人。常に笑いほほ笑みの種を見つけられる。",
    color: "text-red-500",
    loveStyle: "情熱的でサプライズ好き。一緒に新しいことを体験し、精神的に成長し合える関係を望む。束縛を嫌い、自由な愛を好む。",
    group: "NF",
    imgWidth: 110,
  },
  ISTJ: {
    img: "/mbti/sj/istj.png",
    name: "管理者",
    alias: "実用的で事実重視の思考の持ち主",
    description: "実用的で事実重視の思考の持ち主。その信頼性は紛れもない事実。",
    color: "text-red-500",
    loveStyle: "誠実で責任感が強い。言葉よりも行動で愛情を示すタイプ。安定と信頼を何よりも重視し、約束を必ず守る。",
    group: "SJ",
    imgWidth: 140,
  },
  ISFJ: {
    img: "/mbti/sj/isfj.png",
    name: "擁護者",
    alias: "非常に献身的で心の温かい擁護者",
    description: "非常に献身的で心の温かい擁護者。いつでも愛する人を守る準備ができている。",
    color: "text-red-500",
    loveStyle: "思いやりがあり、細やかな気配りができる。相手の世話を焼くことに喜びを感じ、穏やかで安定した家庭的な関係を築く。",
    group: "SJ",
    imgWidth: 200,
  },
  ESTJ: {
    img: "/mbti/sj/estj.png",
    name: "幹部",
    alias: "優秀な管理者",
    description: "優秀な管理者で、物事や人々を管理する能力に長けている。",
    color: "text-red-500",
    loveStyle: "伝統やルールを重んじる。率直に気持ちを伝え、デートの計画もしっかり立てる。安定した将来を見据えた付き合いを好む。",
    group: "SJ",
    imgWidth: 150,
  },
  ESFJ: {
    img: "/mbti/sj/esfj.png",
    name: "領事官",
    alias: "非常に思いやりがあり社交的",
    description: "非常に思いやりがあり社交的で、人気がある。常に熱心に人々に手を差し伸べている。",
    color: "text-red-500",
    loveStyle: "社交的で世話好き。パートナーを喜ばせることが大好きで、常に気にかける。調和を大切にし、愛されている実感を求める。",
    group: "SJ",
    imgWidth: 180,
  },
  ISTP: {
    img: "/mbti/sp/istp.png",
    name: "巨匠",
    alias: "大胆で実践的な思考の持ち主",
    description: "大胆で実践的な思考の持ち主。あらゆる道具を使いこなす。",
    color: "text-red-500",
    loveStyle: "自由を愛し、ベタベタするのは苦手。しかし、信頼した相手には不器用ながらも深い愛を注ぐ。一緒に趣味を楽しめる関係が理想。",
    group: "SP",
    imgWidth: 170,
  },
  ISFP: {
    img: "/mbti/sp/isfp.png",
    name: "冒険者",
    alias: "柔軟で魅力的な芸術家",
    description: "柔軟で魅力的な芸術家。常に新しいことを探索や体験する準備ができている。",
    color: "text-red-500",
    loveStyle: "繊細で感受性が豊か。言葉よりも雰囲気や共有する時間で愛を表現する。束縛せず、お互いの感性を尊重し合える関係を好む。",
    group: "SP",
    imgWidth: 160,
  },
  ESTP: {
    img: "/mbti/sp/estp.png",
    name: "起業家",
    alias: "賢くてエネルギッシュ",
    description: "賢くてエネルギッシュで、非常に鋭い知覚の持ち主。危険と隣り合わせの人生を心から楽しむ。",
    color: "text-red-500",
    loveStyle: "スリルとアクションを求める。退屈なデートは苦手で、一緒にアクティブに楽しめるパートナーを好む。駆け引きよりもストレートなアプローチ。",
    group: "SP",
    imgWidth: 150,
  },
  ESFP: {
    img: "/mbti/sp/esfp.png",
    name: "エンターテイナー",
    alias: "自発的でエネルギッシュ",
    description: "自発的でエネルギッシュで熱心なエンターテイナー。周りが退屈することは決してない。",
    color: "text-red-500",
    loveStyle: "陽気でサプライズ好き。今この瞬間を全力で楽しむことを大切にする。愛情表現が豊かで、笑顔の絶えない明るい関係を築く。",
    group: "SP",
    imgWidth: 140,
  },
}